<?php
/**
 * Created by PhpStorm.
 * Email: wenmang2015@qq.com
 * Date: 2017/11/12
 * Time: 10:47
 * Company: 源码时代重庆校区
 */

namespace backend\components;


use yii\base\ActionFilter;
use yii\web\HttpException;

class RbacFilter extends ActionFilter
{
     //在方法之前执行
    public function beforeAction($action)
    {

       // echo "/".$action->uniqueId;
        if (\Yii::$app->user->can("/".$action->uniqueId)){

            return true;
        }else{
           // header("location:admin/login");
            return false;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}